id: P19968EB3
initial_creation_type: input
source_metadata:
  title: Yeshe Tsogyal Series
  language: fr
  description: 'Texts related to Yeshe Tsogyal (ye shes mtsho rgyal), the consort
    of Guru Padmasambhava:'
  volume:
    3d6478f414834265b31888802c2e82b0:
      title: A Prayer to Khandro Yeshé Tsogyal
      parent: Prayers
    a9191c59cf9348689d6ca7a6f2473f3e:
      title: A Prayer to Lady Yeshe Tsogyal, the Mother
      parent: Prayers
    b8bc7142df0b48eb8ddc1f0bfc9bbaa6:
      title: A Prayer to Yumka Tsogyal
      parent: Prayers
    00cff359559f4a0996aaf30452221aad:
      title: Prayer to Yeshe Tsogyal
      parent: Prayers
    86090f1d8547494e95b32e94d7c3ce3d:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Prayers
    e103255a39b549e3b3c1fa812b4796fa:
      title: Yeshe Tsogyal's Prayer
      parent: Prayers
    d179d104b694439fabdf5ff550255fc7:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Sādhanas
created_at: '2022-03-01T02:03:05.119396'
last_modified_at: '2022-03-01T02:03:05.119399'
